theme = "transparent-tokyonight"

[editor]
line-number = "relative"
mouse = true
# cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = [
  "mode",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "spinner",
]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
"H" = ":buffer-previous"
"L" = ":buffer-next"
