version: "2"

run:
  timeout: 5m
  concurrency: 0

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - copyloopvar
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    errcheck:
      check-type-assertions: true
      check-blank: true

    staticcheck:
      checks:
        - all
        - "-ST1005"
        - "-SA1004"

    exhaustive:
      check: [switch, map]

    exhaustruct:
      exclude:
        - "^net/http.Client$"
        - "^net/http.Cookie$"
        - "^net/http.Request$"
        - "^net/http.Response$"
        - "^net/http.Server$"
        - "^net/http.Transport$"
        - "^net/url.URL$"
        - "^os/exec.Cmd$"
        - "^reflect.StructField$"
        - "^github.com/Shopify/sarama.Config$"
        - "^github.com/Shopify/sarama.ProducerMessage$"
        - "^github.com/mitchellh/mapstructure.DecoderConfig$"
        - "^github.com/prometheus/client_golang/.+Opts$"
        - "^github.com/spf13/cobra.Command$"
        - "^github.com/spf13/cobra.CompletionOptions$"
        - "^github.com/stretchr/testify/mock.Mock$"
        - "^github.com/testcontainers/testcontainers-go.+Request$"
        - "^github.com/testcontainers/testcontainers-go.FromDockerfile$"
        - "^golang.org/x/tools/go/analysis.Analyzer$"
        - "^google.golang.org/protobuf/.+Options$"
        - "^gopkg.in/yaml.v3.Node$"

    funlen:
      lines: 100
      statements: 50
      ignore-comments: true

    gocognit:
      min-complexity: 20

    gocyclo:
      min-complexity: 15

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    mnd:
      ignored-functions:
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets

    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations: [google.golang.org/protobuf]
              reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
          - github.com/satori/go.uuid:
              recommendations: [github.com/google/uuid]
              reason: "satori's package is not maintained"
          - github.com/gofrs/uuid:
              recommendations: [github.com/google/uuid]
              reason: "gofrs' package is not go module"

    govet:
      enable-all: true
      disable: [fieldalignment]
      settings:
        shadow:
          strict: true

    gosec:
      excludes: ["G104"]

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation: [funlen, gocognit, lll]
      require-explanation: true
      require-specific: true

    rowserrcheck:
      packages: [github.com/jmoiron/sqlx]

    revive:
      rules:
        - name: var-naming
        - name: argument-limit
          arguments: [5]
        - name: exported
        - name: indent-error-flow
        - name: receiver-naming

  exclusions:
    presets: [comments, common-false-positives, std-error-handling]
    paths:
      - vendor/
      - third_party/
      - node_modules/
      - .git/
      - '.*\\.pb\\.go$'
      - '.*_gen\\.go$'
      - '.*_mock\\.go$'
    rules:
      - source: "(noinspection|TODO)"
        linters: [godot]
      - source: "//noinspection"
        linters: [gocritic]
      - path: "_test\\.go"
        linters: [bodyclose, dupl, funlen, goconst, gosec, noctx, wrapcheck]

issues:
  max-same-issues: 50
